language: generic 
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t mm0070/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mm0070/docker-react npm run test -- --coverage