language: generic 
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t mm0070/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mm0070/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-643684735051"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY